{% set name = "drjit" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/mitsuba-renderer/drjit/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 1ce377f5f6a255ed5e24f4aa200bed3a4dbfde0e91876e4f945367f5d4a98b77
  - url: https://github.com/mitsuba-renderer/drjit-core/archive/13e9d663dc0eab81dec23357c07157ebf2c07f1f.tar.gz
    sha256: 4c62867a449a940e48ed86506045cbcc521b9c698ee8b76fe6ac78f4a3cfa02f
    folder: ext/drjit-core
  - url: https://github.com/mitsuba-renderer/nanothread/archive/38b77dc96d9b0da248d8eb601eb2bfe9d715068b.tar.gz
    sha256: d6d7f702cfc581f7c50e442d189c70940cd820b5479aa67355dce4717319a934
    folder: ext/drjit-core/ext/nanothread
  - url: https://github.com/Tessil/robin-map/archive/e4316eb284d87f37b93334808bd4aa7e7d819c85.tar.gz
    sha256: a7a435689b0da21d18461e64903869a3a51f20c1fd2f84636e2ff5669c879c16
    folder: ext/drjit-core/ext/robin-map
  - url: https://github.com/mitsuba-renderer/cmake-defaults/archive/c34be21d401ff07266e8945394de9b008d8e503c.tar.gz
    sha256: d0ce9af52784de2ae98c6e9aec004598da617188f27cb8204a1702a0257e63c6
    folder: ext/drjit-core/ext/nanothread/ext/cmake-defaults

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [linux and cuda_compiler_version == 'None']
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != 'None']
    - {{ stdlib('c') }}
    - cmake >=3.11,<=3.18
    - ninja
  host:
    - python
    - pip
    - pybind11
    - scikit-build
  run:
    - python

test:
  imports:
    - drjit.llvm
    - drjit.cuda  # [linux]
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://drjit.readthedocs.io
  summary: A Just-In-Time-Compiler for Differentiable Rendering
  license: BSD-3-Clause AND MIT
  license_family: BSD
  license_file:
    - LICENSE  # BSD-3-Clause
    - ext/drjit-core/LICENSE  # BSD-3-Clause
    - ext/drjit-core/ext/lz4/LICENSE  # BSD-2-Clause
    - ext/drjit-core/ext/nanothread/LICENSE  # BSD-3-Clause
    - ext/drjit-core/ext/robinmap/LICENSE  # MIT
  dev_url: https://github.com/mitsuba-renderer/drjit

extra:
  recipe-maintainers:
    - awvwgk
