{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-sdtm.oak
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/sdtm.oak_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sdtm.oak/sdtm.oak_{{ version }}.tar.gz
  sha256: 988d118b226699668d98ebcbc22bf675c6f9ff95a2e16496ae7b18dbbbb03e3f

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-admiraldev >=1.1.0
    - r-assertthat
    - r-cli
    - r-dplyr >=1.0.0
    - r-pillar
    - r-purrr >=1.0.1
    - r-rlang >=1.0.2
    - r-stringr >=1.4.0
    - r-tibble >=3.2.0
    - r-tidyr >=1.2.0
    - r-vctrs >=0.5.0
  run:
    - r-base
    - r-admiraldev >=1.1.0
    - r-assertthat
    - r-cli
    - r-dplyr >=1.0.0
    - r-pillar
    - r-purrr >=1.0.1
    - r-rlang >=1.0.2
    - r-stringr >=1.4.0
    - r-tibble >=3.2.0
    - r-tidyr >=1.2.0
    - r-vctrs >=0.5.0

test:
  commands:
    - $R -e "library('sdtm.oak')"           # [not win]
    - "\"%R%\" -e \"library('sdtm.oak')\""  # [win]

about:
  home: https://pharmaverse.github.io/sdtm.oak/, https://github.com/pharmaverse/sdtm.oak
  license: Apache-2.0
  summary: An Electronic Data Capture system (EDC) and Data Standard agnostic solution that enables
    the pharmaceutical programming community to develop Clinical Data Interchange Standards
    Consortium (CDISC) Study Data Tabulation Model (SDTM) datasets in R. The reusable
    algorithms concept in 'sdtm.oak' provides a framework for modular programming and
    can potentially automate the conversion of raw clinical data to SDTM through standardized
    SDTM specifications. SDTM is one of the required standards for data submission to
    the Food and Drug Administration (FDA) in the United States and Pharmaceuticals
    and Medical Devices Agency (PMDA) in Japan. SDTM standards are implemented following
    the SDTM Implementation Guide as defined by CDISC <https://www.cdisc.org/standards/foundational/sdtmig>.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
