{% set name = "suitesparsegetpy" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/suitesparsegetpy-{{ version }}.tar.gz
  sha256: 1a9d5efc3ba3d483ec30a453157e222a4c203646c25414660e1992f642840c61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2.0
    - pandas >=2.2.2
    - pymatreader >=1.1
    - requests >=2.0
    - scipy >=1.13
    - toml

test:
  imports:
    - suitesparseget
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/broesler/suitesparseget_py
  summary: Get SuiteSparse matrices into Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - broesler
