context:
  name: "elements"
  version: "3.20.0"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 4e99b59846bc80336326c9001d50c972021895fd8e4aba18874dd1106c086573

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - google-auth
    - google-cloud-storage
    - numpy
    - psutil
    - ruamel.yaml

tests:
  - python:
      imports:
        - elements
      python_version: ${{ python_min }}.*

about:
  homepage: http://github.com/danijar/elements
  summary: Building blocks for productive research.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - noahjutz
