{% set name = "deepqmc" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepqmc-{{ version }}.tar.gz
  sha256: 45bd7b936a0a1a2540ab80cac52e9312f37050fc909d1eaefb4b96f314d61010

build:
  entry_points:
    - deepqmc = deepqmc.app:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >=3.9
    - dm-haiku
    - e3nn-jax
    - h5py
    - hydra-core
    - jax
    - jaxtyping
    - kfac-jax
    - pyscf
    - tensorboard
    - pyyaml
    - tqdm
    - uncertainties

test:
  imports:
    - deepqmc
  commands:
    - pip check
    - deepqmc --help
  requires:
    - pip

about:
  home: https://github.com/deepqmc/deepqmc
  doc_url: https://deepqmc.github.io/
  summary: Deep-learning quantum Monte Carlo for electrons in real space
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
