{% set name = "azure-monitor-opentelemetry" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-monitor-opentelemetry-{{ version }}.tar.gz
  sha256: 40acd9f1e1d7a30f5b6e9654b3cbbcf1b9c9f530831a4cddb85adb112c7e8d96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - azure-core <2.0.0,>=1.24.0
    - azure-core-tracing-opentelemetry >=1.0.0,<1.1.0
    - azure-monitor-opentelemetry-exporter >=1.0.0,<1.1.0
    - opentelemetry-instrumentation-django >=0.42,<1.0
    - opentelemetry-instrumentation-fastapi >=0.42,<1.0
    - opentelemetry-instrumentation-flask >=0.42,<1.0
    - opentelemetry-instrumentation-psycopg2 >=0.42,<1.0
    - opentelemetry-instrumentation-requests >=0.42,<1.0
    - opentelemetry-instrumentation-urllib >=0.42,<1.0
    - opentelemetry-instrumentation-urllib3 >=0.42,<1.0
    - opentelemetry-resource-detector-azure >=0.1.1,<0.2.0

test:
  imports:
    - azure.monitor.opentelemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry
  summary: Microsoft Azure Monitor Opentelemetry Distro Client Library for Python
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - NOTICE.txt

extra:
  recipe-maintainers:
    - awvwgk
