{% set name = "condeltri" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/condeltri-{{ version }}.tar.gz
  sha256: e8e950f8635e7ab7b8af895c3ca4588e549ff852d5a27b7bb352033971abc860

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - scikit-build-core
    - pybind11
    - pip
  run:
    - python >=3.10
    - numpy

test:
  imports:
    - condeltri
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Constrained Delaunay Triangulation
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mdealencar
