{% set name = "molbar" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://git.rwth-aachen.de/bannwarthlab/molbar/-/archive/release_v{{ version }}/molbar-release_v{{ version }}.tar.gz
  sha256: 76e88e12d5637fdf548d4d220c9f3d2739ed82bd1b64d82359b1081b7e71e7af

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - networkx
    - {{ pin_compatible('numpy') }}
    - scipy
    - tqdm
    - joblib

test:
  imports:
    - molbar
    - molbar.barcode
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://git.rwth-aachen.de/bannwarthlab/molbar
  summary: Molecular Barcode (MolBar) as a quantum chemistry-inspired molecular identifier to ensure data uniqueness in databases
  description: |
    This package provides an implementation of the Molecular Barcode (MolBar) as a quantum chemistry-inspired molecular identifier to ensure data uniqueness in databases, supporting organic and inorganic molecules while attempting to describe relative and absolute configuration including centric, axial/helical and planar chirality.

    It does this by fragmentating a molecule into rigid parts which are then idealized with a specialized non-physical force field. The molecule is then described by different matrices encoding topology (connectivity), topography (3D positions of atoms after input unification), and absolute configuration (by calculating a chirality index). The final barcode is the concatenated spectra of these matrices.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
