{% set name = "molbar" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molbar-{{ version }}.tar.gz
  sha256: f6b149c1fdf5d0fc02bce9a809bb30dde0daa7218c2f08dc5e9dc509ecafcf7b

build:
  entry_points:
    - molbar = molbar.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - cmake >=3.18
    - ninja
    - numpy >=1.21
    - pip
    - python
    - scikit-build
    - setuptools >=42
    - wheel
  run:
    - ase
    - dscribe
    - joblib
    - networkx ==3.1
    - numba
    - {{ pin_compatible('numpy') }}
    - pandas
    - python
    - pyyaml
    - scipy
    - tqdm

test:
  imports:
    - molbar
  commands:
    - pip check
    - molbar --help
  requires:
    - pip

about:
  home: https://git.rwth-aachen.de/bannwarthlab/MolBar
  summary: 'Molecular Barcode (MolBar): Molecular Identifier for Organic and Inorganic Molecules'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
