{% set name = "azure-core-tracing-opentelemetry" %}
{% set version = "1.0.0b11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-core-tracing-opentelemetry-{{ version }}.tar.gz
  sha256: a230d1555838b5d07b7594221cd639ea7bc24e29c881e5675e311c6067bad4f5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - opentelemetry-api <2.0.0,>=1.12.0
    - azure-core <2.0.0,>=1.24.0

test:
  imports:
    - azure.core.tracing.ext.opentelemetry_span
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/core/azure-core-tracing-opentelemetry
  summary: Microsoft Azure Azure Core OpenTelemetry plugin Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
