{% set name = "bioemu" %}
{% set version = "1.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/bioemu-{{ version }}.tar.gz
  sha256: 976818fbc1f0f46fb5b292d966cdba5fced01fd658f845986a2f7d5161c1107d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - mdtraj >=1.9.9
    - torch-geometric >=2.6.1
    - pytorch >=2.6.0
    - modelcif >=0.7
    - bio >=1.5.9  # bioconda
    - fire >=0.7.0
    - huggingface_hub
    - hydra-core
    - dm-tree
    - stackprinter
    - typer

test:
  imports:
    - bioemu
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/microsoft/bioemu
  summary: Biomolecular emulator
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE
    - NOTICE.md

extra:
  recipe-maintainers:
    - awvwgk
