{% set name = "scine-art" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scine_art-{{ version }}.tar.gz
  sha256: 9a58baf5bbfd143f971e86ce36a4f309e39c1f97b38c67a58a5505920ffaa3c1

build:
  entry_points:
    - scine_art = scine_art.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - scine-molassembler >=2.0.0,<3.0.0
    - scine-utilities-python >=6.0.0,<9.0.0
    - svgutils
    - networkx
    - numpy
    - dataclasses

test:
  imports:
    - scine_art
  commands:
    # pip check
    - scine_art --help
  requires:
    - pip

about:
  home: https://www.scine.ethz.ch
  dev_url: https://github.com/qcscine/art
  summary: Automated Reaction Templates
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - awvwgk
