{% set name = "azure-monitor-opentelemetry-exporter" %}
{% set version = "1.0.0b22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-monitor-opentelemetry-exporter-{{ version }}.tar.gz
  sha256: 84edad0f142c4c007e2bf93eb4c0fdf79f81ad301d34ccd975a5fd239ecb4eb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - azure-core <2.0.0,>=1.23.0
    - fixedint ==0.1.6
    - msrest >=0.6.10
    - opentelemetry-api >=1.21,<2.0
    - opentelemetry-sdk >=1.21,<2.0

test:
  imports:
    - azure.monitor.opentelemetry.exporter
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/monitor/azure-monitor-opentelemetry-exporter
  summary: Microsoft Azure Monitor Opentelemetry Exporter Client Library for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
