{% set name = "cocina" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cocina-{{ version }}.tar.gz
  sha256: c4f54bb481932864f2ef44b0e990cdfbe6e84e6a1544688e3cc0c42ebbe765ae

build:
  entry_points:
    - cocina = cocina:cli.cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - pyyaml
    - click >=8.2.1,<9

test:
  imports:
    - cocina
  commands:
    - pip check
    - cocina --help
  requires:
    - pip

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  home: https://github.com/SchmidtDSE/cocina
  doc_url: https://github.com/SchmidtDSE/cocina/wiki
  dev_url: https://github.com/SchmidtDSE/cocina
  summary: A collection of tools for building structured Python projects
  description: |
    Cocina is a collection of tools for building structured Python projects.
    It provides sophisticated configuration management, job execution capabilities,
    and a professional CLI interface.

    Core Components:
    - ConfigHandler: Unified configuration management, constants, and environment variables
    - ConfigArgs: Job-specific configuration loading with structured argument access
    - CLI: Command-line interface for project initialization and job execution

extra:
  recipe-maintainers:
    - brookisme