{% set python_min = "3.11" %}
{% set name = "cocina" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cocina-{{ version }}.tar.gz
  sha256: a308ad954ee34d4fea58fe0627fbc453fc08d83f135b471a90e9da1fbafbf4ed

build:
  entry_points:
    - cocina = cocina:cli.cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pyyaml
    - click >=8.2.1,<9

test:
  imports:
    - cocina
  commands:
    - pip check
    - cocina --help
  requires:
    - pip

about:
  license: BSD-3-Clause
  license_file: LICENSE.md
  home: https://github.com/SchmidtDSE/cocina
  doc_url: https://github.com/SchmidtDSE/cocina/wiki
  dev_url: https://github.com/SchmidtDSE/cocina
  summary: A collection of tools for building structured Python projects
  description: |
    Cocina is a collection of tools for building structured Python projects.
    It provides sophisticated configuration management, job execution capabilities,
    and a professional CLI interface.

    Core Components:
    - ConfigHandler: Unified configuration management, constants, and environment variables
    - ConfigArgs: Job-specific configuration loading with structured argument access
    - CLI: Command-line interface for project initialization and job execution

extra:
  recipe-maintainers:
    - brookisme
