{% set name = "opentelemetry-resource-detector-azure" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_resource_detector_azure-{{ version }}.tar.gz
  sha256: 65f0bbb00ec92b021c3a6d8a86fc2f21c8f5a73c012e5d1fa4a12a2d34adc2cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - opentelemetry-sdk >=1.21,<2.0

test:
  imports:
    - opentelemetry_resource_detector_azure
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/resource/opentelemetry-resource-detector-azure
  summary: Azure Resource Detector for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
